### ISSUE TITLE
Possible error in installation instructions

### ISSUE THREAD

**Issue by imagirom** [ReiherGroup/CoRe_optimizer#1]
When executing the pip install (`pip3 install ./core_optimizer`), I get 
```
ERROR: Directory './core_optimizer' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
````
What worked for me is simply `pip install .`.

**Comment by weymutht** [comment]
Thanks for giving our optimizer a try!

I think you have changed into the directory `CoRe_optimizer` after cloning it. In this case, the command `pip install .` is the correct one.

That being said, I just realized that the first code block in the README is a bit misleading. I think it's better to change it to something like
```
git clone <core_optimizer-repository>
pip3 install ./CoRe_optimizer
```
or
```
git clone <core_optimizer-repository>
cd <core_optimizer-repository>
pip3 install .
```
We'll fix that with the next release!

**Comment by imagirom** [comment]
Ah yeah, that's it, so half my bad as well. Thanks for the quick reply. I think few people would really get stuck at this point, I just though I'd point it out as the rest of your readme is so nicely polished :)
